(function(){"use strict";let g=null,p=null;async function u(){if(g?.initialized)return g;if(p)return p;p=(async()=>window.GeminiToolboxStorage?(g||(g=new window.GeminiToolboxStorage,await g.initialize()),g):(console.error("[Pinned Messages] GeminiToolboxStorage class not available"),null))();try{return await p}catch(e){return console.error("[Pinned Messages] Failed to initialize storage:",e),p=null,null}}u().catch(()=>{setTimeout(()=>u(),1e3)});function I(e,t){const i=e.getAttribute("data-message-id")||e.getAttribute("data-message-author-role");if(i)return`${t}-${i}`;const n=e.closest(".conversation-container");if(n?.id)return`${t}-${n.id}`;const r=n?.querySelector("[data-timestamp]")?.dataset?.timestamp;if(r)return`${t}-ts-${r}`;const s=e.textContent.trim(),o=b(s.slice(0,200)),c=s.length.toString(36);return`${t}-c-${o}-${c}`}function b(e){let t=0;for(let i=0;i<e.length;i++){const n=e.charCodeAt(i);t=(t<<5)-t+n,t=t&t}return Math.abs(t).toString(36)}function h(){const e=window.location.pathname.split("/"),t=e.indexOf("app");if(t!==-1&&e[t+1]){const n=e[t+1];if(n&&n!=="default-conversation"&&n.length>0)return n}const i=e.indexOf("chat");return i!==-1&&e[i+1]?e[i+1]:"new-conversation-"+Date.now()}function A(){const e=["title",'[data-test-id="conversation-title"]',".conversation-title","h1"];for(const t of e){const i=document.querySelector(t);if(i&&i.textContent.trim())return i.textContent.trim()}return"Untitled Chat"}function M(e){const t=e?"#8AB4F8":"currentColor";return e?`
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="${t}">
                <path d="M200-120v-640q0-33 23.5-56.5T280-840h400q33 0 56.5 23.5T760-760v640L480-240 200-120Z"/>
            </svg>`:`
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="${t}">
                <path d="M200-120v-640q0-33 23.5-56.5T280-840h400q33 0 56.5 23.5T760-760v640L480-240 200-120Zm80-122 200-86 200 86v-518H280v518Zm0-518h400-400Z"/>
            </svg>`}function S(e,t,i=!1){const n=document.createElement("button");return n.className="gemini-pin-button mdc-icon-button mat-mdc-icon-button mat-mdc-button-base icon-button mat-unthemed",n.setAttribute("data-message-id",e),n.setAttribute("aria-label",i?"Unpin message":"Pin message"),n.setAttribute("title",i?"Unpin message":"Pin message"),n.setAttribute("mat-button",""),n.setAttribute("tabindex","0"),n.innerHTML=`
            <span class="mat-mdc-button-persistent-ripple mdc-icon-button__ripple"></span>
            <div style="transform: scale(0.85); display: flex; align-items: center; justify-content: center;">
                ${M(i)}
            </div>
            <span class="mat-focus-indicator"></span>
            <span class="mat-mdc-button-touch-target"></span>
        `,n.style.cssText=`
            margin: 0;
            padding: 0;
        `,n.addEventListener("mouseenter",()=>{n.style.opacity="1"}),n.addEventListener("mouseleave",()=>{n.style.opacity=""}),n}async function T(e,t,i,n){const r=await u();if(!r||!r.initialized){console.error("[Pinned Messages] Storage not available or not initialized"),window.showToast&&window.showToast("Storage not ready. Please try again.","error");return}try{const s=r.isMessagePinned(i,n),o=t.closest(".conversation-container");if(s)await r.deletePinnedMessage(i),o&&o.classList.remove("gemini-pinned-message"),e.remove(),window.showToast&&window.showToast("Message unpinned","success"),window.geminiAPI&&window.geminiAPI.trackEvent&&window.geminiAPI.trackEvent("message_unpinned",{conversationId:n});else{let c=null,d=!1;try{if(window.geminiAPI&&typeof window.geminiAPI.checkFeatureLimit=="function"&&(c=await window.geminiAPI.checkFeatureLimit("pinnedMessages",!0),d=!0,!c.allowed)){if(window._geminiAPIInternal&&window._geminiAPIInternal.clearPendingIncrement&&window._geminiAPIInternal.clearPendingIncrement("pinnedMessages"),d=!1,window.ensureSidebarOpen&&await window.ensureSidebarOpen(),window.showUpgradeModal&&window.showUpgradeModal("pinnedMessages",c),window.geminiAPI&&window.geminiAPI.trackEvent)try{window.geminiAPI.trackEvent("limit_hit",{feature:"pinnedMessages",count:c.count,limit:c.limit})}catch{}return}}catch(w){console.error("[Pinned Messages] Error checking limit:",w),d&&window._geminiAPIInternal&&window._geminiAPIInternal.clearPendingIncrement&&window._geminiAPIInternal.clearPendingIncrement("pinnedMessages"),window.showToast&&window.showToast("Unable to verify limits. Please try again.","error");return}let l=t.textContent.trim();const y=t.closest("model-response")?"ai":"user";l=l.replace(/Show thinking\s*/gi,""),l=l.replace(/^\s*Thinking\.\.\.\s*/gi,"");let P="";if(o){const w=o.querySelector("user-query-content .query-text");w&&(P=w.textContent.trim())}P&&(l=`Q: ${P}

A: ${l}`);const f=[];o&&(o.querySelectorAll("generated-image img.image, single-image img.image").forEach(a=>{a.src&&!a.src.startsWith("data:")&&f.push({src:a.src,alt:a.alt||"",type:"generated"})}),o.querySelectorAll("img").forEach(a=>{!f.some(k=>k.src===a.src)&&a.src&&!a.src.startsWith("data:")&&a.naturalWidth>50&&f.push({src:a.src,alt:a.alt||"",type:"embedded"})})),await r.createPinnedMessage({messageId:i,conversationId:n,messageContent:l,messageType:y,conversationTitle:A(),images:f}),d&&window._geminiAPIInternal&&window._geminiAPIInternal.clearPendingIncrement&&window._geminiAPIInternal.clearPendingIncrement("pinnedMessages"),o&&(o.classList.add("gemini-pinned-message"),v()),e.remove(),window.showToast&&window.showToast("Message pinned!","success"),window.geminiAPI&&window.geminiAPI.trackEvent&&window.geminiAPI.trackEvent("message_pinned",{messageType:y,hasImages:f.length>0,conversationId:n})}}catch(s){console.error("[Pinned Messages] Error toggling pin:",s),incrementReserved&&window._geminiAPIInternal&&window._geminiAPIInternal.clearPendingIncrement&&window._geminiAPIInternal.clearPendingIncrement("pinnedMessages"),window.showToast&&window.showToast(s.message||"Failed to pin message","error")}}async function C(){try{if(typeof chrome<"u"&&chrome.storage&&chrome.storage.sync){const e=await chrome.storage.sync.get("pinnedMessagesEnabled");return e.pinnedMessagesEnabled!==void 0?e.pinnedMessagesEnabled:!0}}catch{}return!0}function v(){if(document.getElementById("gemini-pinned-styles"))return;const e=document.createElement("style");e.id="gemini-pinned-styles",e.textContent=`
            .gemini-pinned-message {
                border-left: 3px solid var(--gf-accent-primary, #8AB4F8) !important;
                background: color-mix(in srgb, var(--gf-accent-primary, #8AB4F8) 8%, transparent) !important;
                position: relative;
                padding-left: 12px !important;
            }
        `,document.head.appendChild(e)}function x(){document.querySelectorAll(".gemini-pin-button").forEach(i=>{i.remove()}),document.querySelectorAll(".gemini-pinned-message").forEach(i=>{i.classList.remove("gemini-pinned-message")})}async function m(){const e=await u();if(!e||!e.initialized){setTimeout(m,1e3);return}v();const t=h();document.querySelectorAll(".conversation-container").forEach(n=>{const r=n.querySelector("model-response");if(!r||n.textContent.includes("Deciphering User Input")||n.querySelector(".gemini-pin-button"))return;let s=n.querySelector(".response-container-footer .buttons-container-v2");if(s||(s=n.querySelector(".buttons-container-v2")),s||(s=n.querySelector(".actions-container-v2")),s||(s=n.querySelector("message-actions")),!s)return;const o=I(r,t),c=e.isMessagePinned(o,t),d=S(o,t,c);d.addEventListener("click",async()=>{try{await T(d,r,o,t)}catch(y){console.error("[Pinned Messages] Click handler error:",y),window.showToast&&window.showToast("Failed to toggle pin. Please try again.","error")}});const l=s.querySelector(".spacer");l?s.insertBefore(d,l):s.appendChild(d),c&&n.classList.add("gemini-pinned-message")})}function q(){let e=null;const t=new MutationObserver(()=>{clearTimeout(e),e=setTimeout(()=>{m()},500)}),i=document.querySelector("main")||document.body;t.observe(i,{childList:!0,subtree:!0})}function E(){let e=window.location.href,t=h();const i=new MutationObserver(()=>{const r=window.location.href,s=h();(r!==e||s!==t)&&(e=r,t=s,setTimeout(()=>{m()},300))}),n=document.querySelector("title");n&&i.observe(n,{childList:!0,subtree:!0}),setInterval(()=>{const r=window.location.href,s=h();(r!==e||s!==t)&&(e=r,t=s,m())},2e3)}async function _(){v();try{const e=await Promise.race([u(),new Promise((t,i)=>setTimeout(()=>i(new Error("Storage initialization timeout")),1e4))]);if(e&&e.initialized)await m(),q(),E();else throw new Error("Storage not initialized")}catch(e){console.error("[Pinned Messages] \u274C Failed to initialize:",e)}}window.PinnedMessages={initialize:_,injectPinButtons:m,removePinButtons:x,isPinnedMessagesEnabled:C,getStats:async function(){const e=await u();return e&&e.initialized?e.getPinnedMessagesStats():null},getAllPinned:async function(){const e=await u();return e&&e.initialized?e.getAllPinnedMessages():[]}}})();
